CinemaBundle\Entity\TpFilm:
    type: entity
    table: tp_film
    repositoryClass: CinemaBundle\Repository\TpFilmRepository
    indexes:
        id_genre:
            columns:
                - id_genre
        id_distrib:
            columns:
                - id_distrib
    id:
        idFilm:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_film
            generator:
                strategy: IDENTITY
    fields:
        idGenre:
            type: boolean
            nullable: true
            column: id_genre
        idDistrib:
            type: integer
            nullable: true
            unsigned: false
            column: id_distrib
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
        resum:
            type: string
            nullable: false
            length: 255
            fixed: false
        dateDebutAffiche:
            type: date
            nullable: false
            column: date_debut_affiche
        dateFinAffiche:
            type: date
            nullable: false
            column: date_fin_affiche
        dureeMin:
            type: integer
            nullable: false
            unsigned: false
            column: duree_min
        anneeProd:
            type: integer
            nullable: true
            unsigned: false
            column: annee_prod
    lifecycleCallbacks: {  }
